project_name: minitmpl

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - armv7

gitea_urls:
  api: https://git.behzadan.ir/api/v1/

# Need a Gitea token with repo access stored in your environment as GITEA_TOKEN.
release:
  gitea:
    owner: reza
    name: minitmpl

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

