project_name: templar

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7

release:
  github:
    owner: rbehzadan
    name: templar

archives:
  - format: tar.gz
    files:
      - render.sh

